In [1]:
import numpy as np

a = np.array([1,4,6])
a

array([1, 4, 6])

In [2]:
# mean 
np.mean(a)


3.6666666666666665

In [3]:
# min
np.min(a)

1

In [4]:
# max
np.max(a)

6

In [5]:
#std 
np.std(a)

2.0548046676563256

In [6]:

a

array([1, 4, 6])

In [7]:
b = ((1-3.6)**2)+((4-3.6)**2)+((6-3.6)**2)

In [8]:
b/3


4.226666666666667

In [9]:
#var
np.var(a)

4.222222222222222

In [10]:

np.median(a)

4.0

In [11]:
np.mode(a)

AttributeError: module 'numpy' has no attribute 'mode'

In [12]:
from scipy import stats # for statistical calculations
a1 = np.array([[1,3,4,2,2,7],[5,2,2,1,4,1],[3,3,2,2,1,1]])

In [13]:
a1

array([[1, 3, 4, 2, 2, 7],
       [5, 2, 2, 1, 4, 1],
       [3, 3, 2, 2, 1, 1]])

In [14]:
m = stats.mode(a1) # most repeating values
m

ModeResult(mode=array([[1, 3, 2, 2, 1, 1]]), count=array([[1, 2, 2, 2, 1, 2]]))

In [15]:
rv = stats.poisson(2) #avg number of homes - 2

In [16]:
rv.pmf(3)  #we want to find out the likelihood that 3 homes will be sold tomorrow

0.18044704431548356

In [17]:
b = np.array([1,3,2])

In [18]:
np.mean(b)


2.0

In [19]:
np.median(b)

2.0

In [20]:
b = np.array([1,6,4])

In [21]:
np.mean(b)

3.6666666666666665

In [22]:
np.median(b)

4.0