In [1]:
a = [1,2,3]
b = [4,5,6]
for i in range(0,len(a)):
    print(a[i]+b[i])

5
7
9


In [3]:
import numpy as np

In [4]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [5]:
import math

In [6]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [7]:
math.pi # attribute

3.141592653589793

In [9]:
math.pow(2,4) # function

16.0

In [10]:
from math import pi

In [11]:
pi

3.141592653589793

In [13]:
#n dimensions----m*n
#1d array,2d array,3d array

In [14]:
array_1d = np.array([1,2,3])
array_1d

array([1, 2, 3])

In [29]:
array_2d = np.array([[1,2,3],[1,2,3]])

In [30]:
array_2d

array([[1, 2, 3],
       [1, 2, 3]])

In [44]:
array_3d = np.array([[[1,2,3]],[[4,4,5]]])

In [45]:
array_3d

array([[[1, 2, 3]],

       [[4, 4, 5]]])

In [46]:
array_3d.size

6

In [47]:
np.shape(array_3d)

(2, 1, 3)

In [35]:
help(np.shape)

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [48]:
a =np.array([1,2,3])
a

array([1, 2, 3])

In [49]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [50]:
a+b

array([5, 7, 9])

In [51]:
np.add(a,b)

array([5, 7, 9])

In [52]:
np.multiply(a,b)

array([ 4, 10, 18])

In [53]:
a*b

array([ 4, 10, 18])

In [54]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
np.ones((2,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [59]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [64]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [74]:
np.eye((10),k=-8)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.array(range(1,10.6))

TypeError: 'float' object cannot be interpreted as an integer

In [80]:
np.arange(1,10.8,2)

array([1., 3., 5., 7., 9.])

In [83]:
np.linspace(1,10,1000)

array([ 1.        ,  1.00900901,  1.01801802,  1.02702703,  1.03603604,
        1.04504505,  1.05405405,  1.06306306,  1.07207207,  1.08108108,
        1.09009009,  1.0990991 ,  1.10810811,  1.11711712,  1.12612613,
        1.13513514,  1.14414414,  1.15315315,  1.16216216,  1.17117117,
        1.18018018,  1.18918919,  1.1981982 ,  1.20720721,  1.21621622,
        1.22522523,  1.23423423,  1.24324324,  1.25225225,  1.26126126,
        1.27027027,  1.27927928,  1.28828829,  1.2972973 ,  1.30630631,
        1.31531532,  1.32432432,  1.33333333,  1.34234234,  1.35135135,
        1.36036036,  1.36936937,  1.37837838,  1.38738739,  1.3963964 ,
        1.40540541,  1.41441441,  1.42342342,  1.43243243,  1.44144144,
        1.45045045,  1.45945946,  1.46846847,  1.47747748,  1.48648649,
        1.4954955 ,  1.5045045 ,  1.51351351,  1.52252252,  1.53153153,
        1.54054054,  1.54954955,  1.55855856,  1.56756757,  1.57657658,
        1.58558559,  1.59459459,  1.6036036 ,  1.61261261,  1.62

In [87]:
np.random.random((100))

array([0.97397288, 0.95085772, 0.33948561, 0.60583444, 0.81897525,
       0.14285751, 0.8245887 , 0.25684659, 0.38009814, 0.63694085,
       0.81354195, 0.16832311, 0.53554294, 0.48264927, 0.17218218,
       0.00785766, 0.36054746, 0.78070497, 0.39117969, 0.06509342,
       0.68332878, 0.40671157, 0.40782686, 0.16971652, 0.72558148,
       0.94929298, 0.88057613, 0.92498739, 0.26951547, 0.83341124,
       0.95757085, 0.45372385, 0.75473547, 0.10628128, 0.85612626,
       0.31980135, 0.47367937, 0.99413508, 0.24405483, 0.88085992,
       0.86643593, 0.07277679, 0.24377427, 0.89104817, 0.75162816,
       0.76017446, 0.42401616, 0.98229866, 0.50201721, 0.19033239,
       0.05174432, 0.81801698, 0.66965775, 0.96332553, 0.41294418,
       0.88354607, 0.29026836, 0.44540136, 0.55859758, 0.40847989,
       0.50186697, 0.48679191, 0.02526415, 0.121978  , 0.38865152,
       0.06062163, 0.79368984, 0.57005917, 0.95383278, 0.09503389,
       0.8462481 , 0.52343337, 0.86715407, 0.89077964, 0.57613

In [89]:
np.random.rand(10)

array([0.42751264, 0.3405658 , 0.63996704, 0.8942869 , 0.12550263,
       0.16917019, 0.72118121, 0.65524458, 0.02995861, 0.25935162])

In [91]:
np.random.randn(100)

array([-0.21786266,  0.4847372 , -1.87414054,  0.05968286, -0.77636878,
        0.56273202,  0.41709065, -0.14653496,  1.09384802, -1.11343311,
       -0.56507184, -0.17998938, -0.57218166, -0.35661281, -0.42968022,
        0.34237578,  2.44852017,  0.2936091 ,  0.28518207, -0.6494532 ,
        0.79652585, -0.4664516 , -0.90553006, -0.09202305,  0.28542188,
       -0.19083124,  0.021245  , -0.28936302,  0.01137347,  0.57867036,
       -0.01217172, -0.25614068,  0.02930785, -0.43005868, -0.74353674,
       -1.1192431 ,  1.08455242,  0.83888444,  0.06853028, -0.4695682 ,
        0.21063666,  0.79152074,  0.84723709,  0.19909808, -1.35332103,
       -1.11102961,  2.13641574,  0.68171249, -0.02238479, -0.69886624,
       -0.14473077,  1.26230603,  0.57503073,  0.49914522, -0.23326392,
        1.03946819,  0.64370233, -0.2666545 , -0.01830006,  0.5834497 ,
       -0.93661747,  0.7335335 , -2.16823359, -1.17981067, -1.33848418,
        0.58265403, -0.6232557 ,  0.72168471, -0.02557113,  1.07

In [94]:
np.random.randint(1,100,(12,12))

array([[61, 34, 28, 32, 89, 63, 66, 92, 39, 75, 73, 53],
       [19, 51, 11,  8, 99, 41, 19, 45, 79, 21, 85, 54],
       [91, 24, 14, 56, 82, 41, 38,  8,  9, 81, 60, 75],
       [ 1,  8,  3, 77, 93, 58, 12, 89, 65, 92, 90, 80],
       [53, 24, 18, 47, 48, 18,  8, 19, 78, 43, 30, 80],
       [14, 19, 42, 44, 49,  5, 17, 51, 66, 40, 74, 17],
       [24, 30, 48, 84, 64, 56, 17,  1, 60, 56, 85, 51],
       [10, 25,  5, 65, 59, 48,  2,  9, 22, 25, 91, 93],
       [68,  1, 86, 51, 15, 34, 47, 29, 59, 16, 80, 67],
       [ 5, 68, 39,  7, 31, 51, 37, 35, 10, 87, 57, 77],
       [45, 43, 21, 98, 73, 13, 16,  7, 67, 29, 86, 16],
       [ 9, 42, 89, 68, 24, 22, 29,  2, 27,  3, 69, 13]])

In [100]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.transpose(b)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [107]:
a = np.array([[1,2,3]])
a

array([[1, 2, 3]])

In [108]:
np.transpose(a)

array([[1],
       [2],
       [3]])

In [109]:
z = np.array([[1,2],[4,5]])
z

array([[1, 2],
       [4, 5]])

In [112]:
np.linalg.inv(z)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [113]:
np.linalg.det(z)

-2.9999999999999996

In [114]:
z

array([[1, 2],
       [4, 5]])

In [115]:
np.log(z)

array([[0.        , 0.69314718],
       [1.38629436, 1.60943791]])

In [116]:
np.log10(z)

array([[0.        , 0.30103   ],
       [0.60205999, 0.69897   ]])

In [117]:
np.log2(z)

array([[0.        , 1.        ],
       [2.        , 2.32192809]])

In [118]:
np.exp(z)

array([[  2.71828183,   7.3890561 ],
       [ 54.59815003, 148.4131591 ]])

In [119]:
np.sin(z)

array([[ 0.84147098,  0.90929743],
       [-0.7568025 , -0.95892427]])

In [120]:
z

array([[1, 2],
       [4, 5]])

In [126]:
z.reshape(1,-1)

array([[1, 2, 4, 5]])

In [127]:
z.reshape(-1,4)

array([[1, 2, 4, 5]])

In [128]:
help(np.resize)

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Notes
    -----
    i.e. it does not apply interpolation/extrapolation.
    It fills the return array with the required 

In [130]:
np.resize(z,(1,4))

array([[1, 2, 4, 5]])

In [134]:
np.full((1,5),2)

array([[2, 2, 2, 2, 2]])

In [140]:
x = np.array([[[1,2,33],[3,4,5]],[[1,2,23],[45,45,23]]])
x

array([[[ 1,  2, 33],
        [ 3,  4,  5]],

       [[ 1,  2, 23],
        [45, 45, 23]]])

In [141]:
np.shape(x)

(2, 2, 3)

In [142]:
x = np.zeros((2,3,4))

In [143]:
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [144]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [145]:
np.sqrt(4)

2.0

In [147]:
n1 = "abc"
n2 = "cde"
a1=[0]*26
b1=[0]*26
for ele in n1:
    a1[ord(ele)-97]+=1
for ele in n2:
    b1[ord(ele)-97]+=1
print(a1,b1)

[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] [0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [150]:
a1 = [0]*10
c ="bbbb"
for ele in c:
    a1[ord(ele)-97]+=1
    print(a1)

[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 2, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 3, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 4, 0, 0, 0, 0, 0, 0, 0, 0]


In [153]:
ord("c")

99