In [2]:
import numpy as np

In [4]:
array_1d = np.array([1,2,3,4,5])
array_1d

array([1, 2, 3, 4, 5])

In [5]:
array_2d = np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
array_3d = np.array([[[1,2,3],[4,5,6]]])
array_3d

array([[[1, 2, 3],
        [4, 5, 6]]])

In [8]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [9]:
a = np.array(a)
a

array([1, 2, 3])

In [10]:
b = np.array(b)
b

array([4, 5, 6])

In [11]:
a+b

array([5, 7, 9])

In [12]:
1/a

array([1.        , 0.5       , 0.33333333])

In [13]:
np.multiply(a,b)

array([ 4, 10, 18])

In [14]:
arr = np.array(["cse","ece","eee","civil","mech","ece"])
arr

array(['cse', 'ece', 'eee', 'civil', 'mech', 'ece'], dtype='<U5')

In [15]:
arr == "ece"

array([False,  True, False, False, False,  True])

In [16]:
arr!="ece"

array([ True, False,  True,  True,  True, False])

In [17]:
arr1 = np.random.rand(6,4)

In [18]:
arr1

array([[0.87908622, 0.13924042, 0.64734216, 0.74774696],
       [0.16197553, 0.4402364 , 0.95903118, 0.85729419],
       [0.51627927, 0.09281424, 0.59610874, 0.26310137],
       [0.43459376, 0.34991019, 0.5629846 , 0.84734347],
       [0.48643071, 0.18442697, 0.25423394, 0.28310957],
       [0.46061457, 0.26642764, 0.80800268, 0.36824606]])

In [19]:
arr1[arr == "ece"]

array([[0.16197553, 0.4402364 , 0.95903118, 0.85729419],
       [0.46061457, 0.26642764, 0.80800268, 0.36824606]])

In [22]:
arr1[arr1>0] = 10

In [23]:
arr1

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.ones((3,4),dtype = str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [29]:
np.ones((3,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])